(this.webpackJsonpedulynreact = this.webpackJsonpedulynreact || []).push([[0],
{
    100: function (e) {
        e.exports = JSON.parse('{"backgroundImage":"vd-bg.jpg"}')
    },
    101: function (e) {
        e.exports = JSON.parse('[{"id":"1","postImg":"blog_c-01.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postCategory":"Web Design","commentNumber":"23","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic. Sequi obcaecati possimus repudiandae sit omnis accusantium","authorLink":"/blog-details"},{"id":"2","postImg":"blog_c-02.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postCategory":"Web Design","commentNumber":"23","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic. Sequi obcaecati possimus repudiandae sit omnis accusantium","authorLink":"/blog-details"},{"id":"3","postImg":"blog_c-03.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postCategory":"Web Design","commentNumber":"23","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic. Sequi obcaecati possimus repudiandae sit omnis accusantium","authorLink":"/blog-details"},{"id":"4","postImg":"blog_c-04.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postCategory":"Web Design","commentNumber":"23","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic. Sequi obcaecati possimus repudiandae sit omnis accusantium","authorLink":"/blog-details"}]')
    },
    102: function (e) {
        e.exports = JSON.parse('[{"id":"1","imgUrl":"pop-course-1.jpg","blogDate":"April 12,2020","blogTitle":"Php & mySql Adv Programming","blogLink":"/blog-details"},{"id":"2","imgUrl":"pop-course-2.jpg","blogDate":"April 12,2020","blogTitle":"Microsoft Excel for Beginner","blogLink":"/blog-details"},{"id":"3","imgUrl":"pop-course-3.jpg","blogDate":"April 12,2020","blogTitle":"Digital Marketing Course","blogLink":"/blog-details"},{"id":"4","imgUrl":"pop-course-4.jpg","blogDate":"April 12,2020","blogTitle":"Beckend Dev With Wordpress","blogLink":"/blog-details"}]')
    },
    103: function (e) {
        e.exports = JSON.parse('[{"id":"1","postImg":"blog_c-02.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic.","postDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis, quos commodi Quasi laudantium, voluptatem velit necessitatibus.","authorLink":"/"},{"id":"2","postImg":"blog_c-03.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic.","postDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis, quos commodi Quasi laudantium, voluptatem velit necessitatibus.","authorLink":"/"},{"id":"3","postImg":"blog_c-05.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic.","postDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis, quos commodi Quasi laudantium, voluptatem velit necessitatibus.","authorLink":"/"},{"id":"4","postImg":"blog_c-06.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic.","postDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis, quos commodi Quasi laudantium, voluptatem velit necessitatibus.","authorLink":"/"},{"id":"5","postImg":"blog_c-07.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic.","postDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis, quos commodi Quasi laudantium, voluptatem velit necessitatibus.","authorLink":"/"},{"id":"6","postImg":"blog_c-08.jpg","authorImg":"author.jpg","authorName":"Medison Azar","postLink":"/blog-details","postDate":"April 23, 2020","postTitle":"Ratione omnis consequuntur placeae consol fugit eaque vitae hic.","postDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis, quos commodi Quasi laudantium, voluptatem velit necessitatibus.","authorLink":"/"}]')
    },
    104: function (e) {
        e.exports = JSON.parse('[{"id":"1","productImg":"product-01.jpg","productTitle":"Product 01","productUrl":"/product-details","price":"$99.00","discount":"-30%"},{"id":"2","productImg":"product-02.jpg","productTitle":"Product 02","productUrl":"/product-details","price":"$99.00","discount":"-25%"},{"id":"3","productImg":"product-03.jpg","productTitle":"Product 03","productUrl":"/product-details","price":"$99.00","discount":"-27%"},{"id":"4","productImg":"product-04.jpg","productTitle":"Product 04","productUrl":"/product-details","price":"$99.00","discount":"-15%"},{"id":"5","productImg":"product-05.jpg","productTitle":"Product 05","productUrl":"/product-details","price":"$99.00","discount":"-21%"},{"id":"6","productImg":"product-06.jpg","productTitle":"Product 06","productUrl":"/product-details","price":"$99.00","discount":"-17%"},{"id":"7","productImg":"product-07.jpg","productTitle":"Product 07","productUrl":"/product-details","price":"$99.00","discount":"-36%"},{"id":"8","productImg":"product-08.jpg","productTitle":"Product 08","productUrl":"/product-details","price":"$99.00","discount":"-29%"},{"id":"9","productImg":"product-09.jpg","productTitle":"Product 09","productUrl":"/product-details","price":"$99.00","discount":"-33%"}]')
    },
    105: function (e) {
        e.exports = JSON.parse('[{"productImg":"product-01.jpg"},{"productImg":"product-02.jpg"},{"productImg":"product-03.jpg"},{"productImg":"product-04.jpg"},{"productImg":"product-05.jpg"}]')
    },
    32: function (e) {
        e.exports = JSON.parse('{"secTitle":"We Have Experienced Professionals & We Do Our Best To Achieve Your Goal. Your Happiness Is Our First Priority.","secDesc":"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis error ut provident vel repellendus nihil atque possimus aliquam, mollitia tempora neque voluptate debitis illum veniam.","dataList":[{"iconTitle":"Best Quality Courses","iconSubtitle":"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis error ut provident vel repellendus nihil atque possimus aliquam"},{"iconTitle":"Best Quality Courses","iconSubtitle":"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis error ut provident vel repellendus nihil atque possimus aliquam"},{"iconTitle":"Best Quality Courses","iconSubtitle":"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis error ut provident vel repellendus nihil atque possimus aliquam"}],"aboutImageOne":"about-2.jpg","aboutImageTwo":"about-3.jpg","experianceYear":"15"}')
    },
    35: function (e) {
        e.exports = JSON.parse('{"mainImage":"about-1.jpg","videoBackground":"vd-bg.jpg","title":"We Have Experienced Professionals & We Do Our Best To Achieve Your Goal. Your Happiness Is Our First Priority.","desc1":"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis error ut provident vel repellendus nihil atque possimus aliquam, mollitia tempora neque voluptate debitis illum veniam.Numquam blanditiis dignissimos laboriosam illum ut officia.","desc2":"Nam aperiam autem nesciunt perferendis id. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas nulla sequi pariatur quam animi ipsum molestias assumenda cumque."}')
    },
    36: function (e) {
        e.exports = JSON.parse('[{"id":"1","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."},{"id":"2","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."},{"id":"3","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."},{"id":"4","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."},{"id":"5","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."},{"id":"6","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."},{"id":"7","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."},{"id":"8","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon officia aute."}]')
    },
    41: function (e) {
        e.exports = JSON.parse('{"heroBackground":"hero-bg.jpg","heroTitle":"Best University In This Region Join With Us Today.","heroSubtitle":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam tempore laudantium pariatur ipsa delectus odit sequi dolor.","heroRoundShape":"r-shape.png"}')
    },
    50: function (e) {
        e.exports = JSON.parse('[{"id":"1","imgUrl":"course-1.jpg","authorImg":"author.jpg","authorName":"John Doe","authorCourses":"13 Courses","price":"$20","courseTitle":"Php & mySql Programming","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"2","imgUrl":"course-2.jpg","authorImg":"author.jpg","authorName":"Jara Sen","authorCourses":"21 Courses","price":"$13","courseTitle":"Microsoft Excel for Beginner","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"3","imgUrl":"course-3.jpg","authorImg":"author.jpg","authorName":"Kim Chang","authorCourses":"26 Courses","price":"$19","courseTitle":"Digital Marketing Course","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"4","imgUrl":"course-4.jpg","authorImg":"author.jpg","authorName":"Jim Hunt","authorCourses":"09 Courses","price":"$15","courseTitle":"Zero to Hero in Python 3","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"5","imgUrl":"course-5.jpg","authorImg":"author.jpg","authorName":"Sara Kim","authorCourses":"17 Courses","price":"$21","courseTitle":"React JS, Angular & Vue JS","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"6","imgUrl":"course-6.jpg","authorImg":"author.jpg","authorName":"Shon Doe","authorCourses":"31 Courses","price":"$24","courseTitle":"Laravel API Development","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"}]')
    },
    51: function (e) {
        e.exports = JSON.parse('{"secTitle":"Lets See What Our Valuable Students Think About Us. Their Testimonials.","backgroundImage":"vd-bg.jpg","dataList":[{"id":"1","testimonialTitle":"It is great to be a part of this community.","testimonialDesc":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitation maior. Placeat repellat, et totam optio. Sequi qui laborum ratione cumque tempo totam voluptatum.","authorImg":"testimonial-1.jpg","authorName":"David Show","authorTitle":"Developer"},{"id":"2","testimonialTitle":"It is great to be a part of this community.","testimonialDesc":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitation maior. Placeat repellat, et totam optio. Sequi qui laborum ratione cumque tempo totam voluptatum.","authorImg":"testimonial-2.jpg","authorName":"Tom Parker","authorTitle":"Programmer"}]}')
    },
    52: function (e) {
        e.exports = JSON.parse('{"secTitle":"Get Free Training Course On Web Design For This Week. It\'s Limited Time Only. Hurry Up To Get This Course.","subTitle":"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deserunt, molestiae modi quas rerum animi placeat aut iusto quae dolore officiis. Odio totam debitis quos voluptatib dolorem quae sequi ab velit.","formBackground":"vd-bg.jpg"}')
    },
    61: function (e) {
        e.exports = JSON.parse('{"secTitle":"We Do What We Love To Do. Find the Best Course To Fit Your Needs.","dataList":[{"id":"1","targetId":"desi","imgUrl":"course-1.jpg","authorImg":"author.jpg","authorName":"John Doe","authorCourses":"13 Courses","price":"$20","courseTitle":"Php & mySql Programming","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"2","targetId":"deve","imgUrl":"course-2.jpg","authorImg":"author.jpg","authorName":"Jara Sen","authorCourses":"21 Courses","price":"$13","courseTitle":"Microsoft Excel for Beginner","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"3","targetId":"seo","imgUrl":"course-3.jpg","authorImg":"author.jpg","authorName":"Kim Chang","authorCourses":"26 Courses","price":"$19","courseTitle":"Digital Marketing Course","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"4","targetId":"prog","imgUrl":"course-4.jpg","authorImg":"author.jpg","authorName":"Jim Hunt","authorCourses":"09 Courses","price":"$15","courseTitle":"Zero to Hero in Python 3","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"5","targetId":"desi","imgUrl":"course-5.jpg","authorImg":"author.jpg","authorName":"Sara Kim","authorCourses":"17 Courses","price":"$21","courseTitle":"React JS, Angular & Vue JS","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"6","targetId":"deve","imgUrl":"course-6.jpg","authorImg":"author.jpg","authorName":"Shon Doe","authorCourses":"31 Courses","price":"$24","courseTitle":"Laravel API Development","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"}]}')
    },
    62: function (e) {
        e.exports = JSON.parse('{"eventDataList":[{"id":"1","eventDate":"25 March","eventTitle":"2020 admidion fair going on this week","eventTime":"5:30pm - 7.00pm","eventLocation":"Newyork,NY.","eventdesc":"Lorem ipsum dolor sit amet consectetur. Como Ssee hou","eventLink":"/event-details"},{"id":"2","eventDate":"25 March","eventTitle":"2020 admidion fair going on this week","eventTime":"5:30pm - 7.00pm","eventLocation":"Newyork,NY.","eventdesc":"Lorem ipsum dolor sit amet consectetur. Como Ssee hou","eventLink":"/event-details"},{"id":"3","eventDate":"25 March","eventTitle":"2020 admidion fair going on this week","eventTime":"5:30pm - 7.00pm","eventLocation":"Newyork,NY.","eventdesc":"Lorem ipsum dolor sit amet consectetur. Como Ssee hou","eventLink":"/event-details"}],"faqDataList":[{"id":"1","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon."},{"id":"2","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid."},{"id":"3","faqTitle":"I don\'t know What should I write here?","faqDesc":"Anim pariatur cliche reprehenderit, enim eiusm high life accusamus terry richardson ad squid. 3 wolf moon."}]}')
    },
    63: function (e) {
        e.exports = JSON.parse('{"secTitle":"We Have Fantustic Team To Help Student And They Are Always Ready.","dataList":[{"id":"1","personImage":"team-1.jpg","personName":"Emily Perrey","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"2","personImage":"team-2.jpg","personName":"Justin Timbr","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"3","personImage":"team-3.jpg","personName":"Medison White","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"4","personImage":"team-4.jpg","personName":"Mark Shadow","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"5","personImage":"team-5.jpg","personName":"Katy Perrey","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}}]}')
    },
    64: function (e) {
        e.exports = JSON.parse('{"secTitle":"If You have Any Question Please Don\'t Hesitate To Contact Us","backgroundImage":"vd-bg.jpg"}')
    },
    65: function (e) {
        e.exports = JSON.parse('{"secTitle":"Lets See What We Can Show To You Our Useful Blog Article Post.","dataList":[{"id":"1","postImg":"blog-1.jpg","postLink":"/blog-details","postDate":"25 Mar","postTitle":"Libero nulla illo quam iure reiciendis maxime.","postExcerpt":"Lorem ipsum dolor sit amet consecte adipisicing elit. Quisquam excepturi eum necessitatibus.","authorLink":"/","commentLink":"/","likeLink":"/"},{"id":"2","postImg":"blog-2.jpg","postLink":"/blog-details","postDate":"25 Mar","postTitle":"Libero nulla illo quam iure reiciendis maxime.","postExcerpt":"Lorem ipsum dolor sit amet consecte adipisicing elit. Quisquam excepturi eum necessitatibus.","authorLink":"/","commentLink":"/","likeLink":"/"},{"id":"3","postImg":"blog-3.jpg","postLink":"/blog-details","postDate":"25 Mar","postTitle":"Libero nulla illo quam iure reiciendis maxime.","postExcerpt":"Lorem ipsum dolor sit amet consecte adipisicing elit. Quisquam excepturi eum necessitatibus.","authorLink":"/","commentLink":"/","likeLink":"/"},{"id":"4","postImg":"blog-4.jpg","postLink":"/blog-details","postDate":"25 Mar","postTitle":"Libero nulla illo quam iure reiciendis maxime.","postExcerpt":"Lorem ipsum dolor sit amet consecte adipisicing elit. Quisquam excepturi eum necessitatibus.","authorLink":"/","commentLink":"/","likeLink":"/"}]}')
    },
    66: function (e) {
        e.exports = JSON.parse('{"secTitle":"Checkout Our Features To Know Why We Are Best In This Business","dataList":[{"id":"1","boxIcon":"flaticon-thumbs-like","title":"Popular Courses","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."},{"id":"2","boxIcon":"flaticon-reading","title":"Modern Library","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."},{"id":"3","boxIcon":"flaticon-teacher","title":"Qualified Teacher","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."},{"id":"4","boxIcon":"flaticon-unlimited","title":"Unlimited Courses","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."},{"id":"5","boxIcon":"flaticon-locations","title":"Many Locations","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."},{"id":"6","boxIcon":"flaticon-support","title":"Online Support","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."}]}')
    },
    67: function (e) {
        e.exports = JSON.parse('{"secTitle":"We Do What We Love To Do. Find the Best Course To Fit Your Needs.","dataList":[{"id":"1","imgUrl":"course-1.jpg","authorImg":"author.jpg","authorName":"John Doe","authorCourses":"13 Courses","price":"$20","courseTitle":"Php & mySql Programming","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"2","imgUrl":"course-2.jpg","authorImg":"author.jpg","authorName":"Jara Sen","authorCourses":"21 Courses","price":"$13","courseTitle":"Microsoft Excel for Beginner","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"3","imgUrl":"course-3.jpg","authorImg":"author.jpg","authorName":"Kim Chang","authorCourses":"26 Courses","price":"$19","courseTitle":"Digital Marketing Course","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"4","imgUrl":"course-4.jpg","authorImg":"author.jpg","authorName":"Jim Hunt","authorCourses":"09 Courses","price":"$15","courseTitle":"Zero to Hero in Python 3","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"}]}')
    },
    68: function (e) {
        e.exports = JSON.parse('{"backgroundImage":"vd-bg.jpg","secTitle":"Lets Have A Look At Some Of Achievements For Years We Get."}')
    },
    86: function (e) {
        e.exports = JSON.parse('[{"id":"1","backgroundImage":"slider-1.jpg","uniqClass":"slider-box slider-box1","title":"Welcome To Edulyn.","desc":"Best University In This Region Join With Us Today","btnOneLink":"course-grid","btnTwoLink":"contact"},{"id":"2","backgroundImage":"slider-2.jpg","uniqClass":"slider-box slider-box2 text-right","title":"Welcome To Edulyn.","desc":"Best University In This Region Join With Us Today","btnOneLink":"course-grid","btnTwoLink":"contact"}]')
    },
    87: function (e) {
        e.exports = JSON.parse('[{"id":"1","uniqClass":"box-icon box1","boxIcon":"flaticon-thumbs-like","title":"Popular Courses","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."},{"id":"2","uniqClass":"box-icon box2","boxIcon":"flaticon-reading","title":"Modern Library","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."},{"id":"3","uniqClass":"box-icon box3","boxIcon":"flaticon-teacher","title":"Qualified Teacher","subTitle":"Lorem ipsum dolor sit, amet consectetur elit."}]')
    },
    88: function (e) {
        e.exports = JSON.parse('{"backgroundImage":"vd-bg.jpg"}')
    },
    89: function (e) {
        e.exports = JSON.parse('[{"galleryImage":"imagegallery-01.jpg"},{"galleryImage":"imagegallery-02.jpg"},{"galleryImage":"imagegallery-03.jpg"},{"galleryImage":"imagegallery-04.jpg"}]')
    },
    90: function (e) {
        e.exports = JSON.parse('{"backgroundImage":"vd-bg.jpg"}')
    },
    91: function (e) {
        e.exports = JSON.parse('[{"id":"1","imgUrl":"pop-course-1.jpg","price":"$20.00","courseTitle":"Php & mySql Adv Programming","courseLink":"/course-details"},{"id":"2","imgUrl":"pop-course-2.jpg","price":"$13.00","courseTitle":"Microsoft Excel for Beginner","courseLink":"/course-details"},{"id":"3","imgUrl":"pop-course-3.jpg","price":"$19.00","courseTitle":"Digital Marketing Course","courseLink":"/course-details"},{"id":"4","imgUrl":"pop-course-4.jpg","price":"$16.00","courseTitle":"Beckend Dev With Wordpress","courseLink":"/course-details"}]')
    },
    92: function (e) {
        e.exports = JSON.parse('[{"id":"1","personImage":"team-1.jpg","personName":"Emily Perrey","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"2","personImage":"team-2.jpg","personName":"Justin Timbr","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"3","personImage":"team-3.jpg","personName":"Medison White","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"4","personImage":"team-4.jpg","personName":"Mark Shadow","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"5","personImage":"team-5.jpg","personName":"Katy Perrey","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"6","personImage":"team-6.jpg","personName":"David Smith","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"7","personImage":"team-7.jpg","personName":"Ely Parker","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"8","personImage":"team-8.jpg","personName":"Shown Marsh","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"9","personImage":"team-9.jpg","personName":"Jinnat Watson","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"10","personImage":"team-10.jpg","personName":"Alister Cook","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"11","personImage":"team-11.jpg","personName":"Sam Perrey","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"12","personImage":"team-12.jpg","personName":"Katerin White","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}}]')
    },
    93: function (e) {
        e.exports = JSON.parse('[{"id":"1","imgUrl":"course-1.jpg","authorImg":"author.jpg","authorName":"John Doe","authorCourses":"13 Courses","price":"$20","courseTitle":"Php & mySql Programming","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"2","imgUrl":"course-2.jpg","authorImg":"author.jpg","authorName":"Jara Sen","authorCourses":"21 Courses","price":"$13","courseTitle":"Microsoft Excel for Beginner","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"3","imgUrl":"course-3.jpg","authorImg":"author.jpg","authorName":"Kim Chang","authorCourses":"26 Courses","price":"$19","courseTitle":"Digital Marketing Course","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"},{"id":"4","imgUrl":"course-4.jpg","authorImg":"author.jpg","authorName":"Jim Hunt","authorCourses":"09 Courses","price":"$15","courseTitle":"Zero to Hero in Python 3","courseDesc":"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusamus hic ea in autem debitis minima.","courseLink":"/course-details"}]')
    },
    94: function (e) {
        e.exports = JSON.parse('[{"galleryImage":"imagegallery-01.jpg"},{"galleryImage":"imagegallery-02.jpg"},{"galleryImage":"imagegallery-03.jpg"},{"galleryImage":"imagegallery-04.jpg"},{"galleryImage":"imagegallery-05.jpg"},{"galleryImage":"imagegallery-06.jpg"},{"galleryImage":"imagegallery-07.jpg"},{"galleryImage":"imagegallery-08.jpg"},{"galleryImage":"imagegallery-09.jpg"}]')
    },
    95: function (e) {
        e.exports = JSON.parse('[{"id":"1","eventImg":"event-01.jpg","eventDate":"25 March","eventTitle":"Ratione omnis consequuntur placeae consol.","eventTime":"7:30pm","eventLocation":"795 South Park Avenue, CA 94107.","eventdesc":"Fugiat et aperiam similique, perferendis maiores tenetur voluptatem consequuntur harum unde illo alias mollitia a cumque.","eventLink":"/event-details"},{"id":"2","eventImg":"event-02.jpg","eventDate":"25 March","eventTitle":"Ratione omnis consequuntur placeae consol.","eventTime":"7:30pm","eventLocation":"795 South Park Avenue, CA 94107.","eventdesc":"Fugiat et aperiam similique, perferendis maiores tenetur voluptatem consequuntur harum unde illo alias mollitia a cumque.","eventLink":"/event-details"},{"id":"3","eventImg":"event-03.jpg","eventDate":"25 March","eventTitle":"Ratione omnis consequuntur placeae consol.","eventTime":"7:30pm","eventLocation":"795 South Park Avenue, CA 94107.","eventdesc":"Fugiat et aperiam similique, perferendis maiores tenetur voluptatem consequuntur harum unde illo alias mollitia a cumque.","eventLink":"/event-details"},{"id":"4","eventImg":"event-04.jpg","eventDate":"25 March","eventTitle":"Ratione omnis consequuntur placeae consol.","eventTime":"7:30pm","eventLocation":"795 South Park Avenue, CA 94107.","eventdesc":"Fugiat et aperiam similique, perferendis maiores tenetur voluptatem consequuntur harum unde illo alias mollitia a cumque.","eventLink":"/event-details"},{"id":"5","eventImg":"event-05.jpg","eventDate":"25 March","eventTitle":"Ratione omnis consequuntur placeae consol.","eventTime":"7:30pm","eventLocation":"795 South Park Avenue, CA 94107.","eventdesc":"Fugiat et aperiam similique, perferendis maiores tenetur voluptatem consequuntur harum unde illo alias mollitia a cumque.","eventLink":"/event-details"},{"id":"6","eventImg":"event-06.jpg","eventDate":"25 March","eventTitle":"Ratione omnis consequuntur placeae consol.","eventTime":"7:30pm","eventLocation":"795 South Park Avenue, CA 94107.","eventdesc":"Fugiat et aperiam similique, perferendis maiores tenetur voluptatem consequuntur harum unde illo alias mollitia a cumque.","eventLink":"/event-details"},{"id":"7","eventImg":"event-07.jpg","eventDate":"25 March","eventTitle":"Ratione omnis consequuntur placeae consol.","eventTime":"7:30pm","eventLocation":"795 South Park Avenue, CA 94107.","eventdesc":"Fugiat et aperiam similique, perferendis maiores tenetur voluptatem consequuntur harum unde illo alias mollitia a cumque.","eventLink":"/event-details"}]')
    },
    96: function (e) {
        e.exports = JSON.parse('[{"id":"1","personImage":"team-1.jpg","personName":"Emily Perrey","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"2","personImage":"team-2.jpg","personName":"Justin Timbr","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"3","personImage":"team-3.jpg","personName":"Medison White","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}},{"id":"4","personImage":"team-4.jpg","personName":"Mark Shadow","personTitle":"Teacher","socialLinks":{"facebook":"//www.facebook.com","twitter":"//www.twitter.com","linkedin":"//www.linkedin.com","youtube":"//www.youtube.com"}}]')
    },
    99: function (e) {
        e.exports = JSON.parse('{"backgroundImage":"vd-bg.jpg"}')
    }
}, [[110, 1, 2]]]);
//# sourceMappingURL=main.71041892.chunk.js.map
