const payment = {
  GET_MY_INVOICES_REQUEST: 'GET_MY_INVOICES_REQUEST',
  GET_MY_INVOICES_SUCCESS: 'GET_MY_INVOICES_SUCCESS',
  GET_MY_INVOICES_ERROR: 'GET_MY_INVOICES_ERROR',

  GET_MY_TRANSACTIONS_REQUEST: 'GET_MY_TRANSACTIONS_REQUEST',
  GET_MY_TRANSACTIONS_SUCCESS: 'GET_MY_TRANSACTIONS_SUCCESS',
  GET_MY_TRANSACTIONS_ERROR: 'GET_MY_TRANSACTIONS_ERROR',

  SEARCH_PAYMENT_REQUEST: 'SEARCH_PAYMENT_REQUEST',
  SEARCH_PAYMENT_SUCCESS: 'SEARCH_PAYMENT_SUCCESS',
  SEARCH_PAYMENT_ERROR: 'SEARCH_PAYMENT_ERROR',

  getMyInvoices: (data) => ({
    type: payment.GET_MY_INVOICES_REQUEST,
    data,
  }),

  getMyTransactions: (data) => ({
    type: payment.GET_MY_TRANSACTIONS_REQUEST,
    data,
  }),

  searchPayment: (prn) => ({
    type: payment.SEARCH_PAYMENT_REQUEST,
    prn,
  }),
};

export default payment;
