const paymentReference = {
  GENERATE_PAYMENT_REFERENCE_REQUEST: 'GENERATE_PAYMENT_REFERENCE_REQUEST',
  GENERATE_PAYMENT_REFERENCE_SUCCESS: 'GENERATE_PAYMENT_REFERENCE_SUCCESS',
  GENERATE_PAYMENT_REFERENCE_ERROR: 'GENERATE_PAYMENT_REFERENCE_ERROR',

  GETTING_PAYMENT_REFERENCES_REQUEST: 'GETTING_PAYMENT_REFERENCES_REQUEST',
  GETTING_PAYMENT_REFERENCES_SUCCESS: 'GETTING_PAYMENT_REFERENCES_SUCCESS',
  GETTING_PAYMENT_REFERENCES_ERROR: 'GETTING_PAYMENT_REFERENCES_ERROR',

  generatePaymentReference: (data, referenceType = 'invoice') => ({
    type: paymentReference.GENERATE_PAYMENT_REFERENCE_REQUEST,
    data,
    referenceType,
  }),

  getPaymentReferences: (data) => ({
    type: paymentReference.GETTING_PAYMENT_REFERENCES_REQUEST,
    data,
  }),
};

export default paymentReference;
